"""empty message

Revision ID: 14fbb63dccf6
Revises: c598a8e77c3c
Create Date: 2018-03-08 16:06:54.490593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14fbb63dccf6'
down_revision = 'c598a8e77c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love', sa.Column('from_comment', sa.String(length=256), nullable=True))
    op.add_column('love', sa.Column('part_comment', sa.String(length=256), nullable=True))
    op.add_column('love', sa.Column('part_id', sa.Integer(), nullable=True))
    op.add_column('love', sa.Column('to_comment', sa.String(length=256), nullable=True))
    op.drop_column('love', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love', sa.Column('comment', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('love', 'to_comment')
    op.drop_column('love', 'part_id')
    op.drop_column('love', 'part_comment')
    op.drop_column('love', 'from_comment')
    # ### end Alembic commands ###
