"""empty message

Revision ID: ba3670d0566b
Revises: 6c06a1d5d803
Create Date: 2018-03-08 13:27:51.875336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3670d0566b'
down_revision = '6c06a1d5d803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notice_form_id_key', 'notice', type_='unique')
    op.drop_column('notice', 'form_id')
    op.drop_column('notice', 'content')
    op.drop_column('notice', 'to_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notice', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notice', sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('notice_form_id_key', 'notice', ['form_id'])
    # ### end Alembic commands ###
